import { z } from "zod";
import { RestClient } from "../../rest-client.js";
import { accountFilterSchema, buildAccountFilter } from "./filters.js";
import { issuePlan } from "../../preview/plan-commit.js";
import { ResourceSpec, makeResourceTools, readFresh, readWithEtag } from "./resource-write.js";

// === RESOURCE SPECS + GENERATED PLAN/COMMIT PAIRS ===
//
// Every config resource shares one write contract, so each is described once here and its
// plan/commit pair is generated by makeResourceTools. Shared behaviour — ETag handling, stripping
// server-managed fields, disclosure wording — therefore lives in resource-write.ts and reaches
// all of them at once; previously each resource carried its own copy and fixes arrived one by one.
const SYMBOL_SPEC: ResourceSpec = {
  label: "symbol",
  getPath: (id) => `/admin/symbols/get/${id}`,
  editPath: "/admin/symbols/edit",
  deletePath: "/admin/symbols/delete",
  idKey: "symbolId",
  nameKey: "name",
};

const GROUP_SPEC: ResourceSpec = {
  label: "group",
  getPath: (id) => `/admin/groups/get/${id}`,
  editPath: "/admin/groups/edit",
  deletePath: "/admin/groups/delete",
  idKey: "groupId",
  nameKey: "name",
};

const ACCOUNT_SPEC: ResourceSpec = {
  label: "trading account",
  getPath: (id) => `/admin/accounts/get/${id}`,
  editPath: "/admin/accounts/edit",
  deletePath: "/admin/accounts/delete",
  idKey: "accountId",
};

const CLIENT_SPEC: ResourceSpec = {
  label: "client",
  getPath: (id) => `/admin/clients/get/${id}`,
  editPath: "/admin/clients/edit",
  deletePath: "/admin/clients/delete",
  idKey: "clientId",
};

const CONNECTOR_SPEC: ResourceSpec = {
  label: "liquidity connector",
  getPath: (id) => `/admin/liquidity/get/${id}`,
  editPath: "/admin/liquidity/edit",
  deletePath: "/admin/liquidity/delete",
  idKey: "connectorId",
};

const HOLIDAY_SPEC: ResourceSpec = {
  label: "holiday",
  getPath: (id) => `/admin/holidays/get/${id}`,
  editPath: "/admin/holidays/edit",
  deletePath: "/admin/holidays/delete",
  idKey: "holidayId",
  nameKey: "description",
};

const MANAGER_SPEC: ResourceSpec = {
  label: "manager",
  getPath: (id) => `/admin/managers/get/${id}`,
  editPath: "/admin/managers/edit",
  deletePath: "/admin/managers/delete",
  idKey: "accountId",
};

const symbolTools = makeResourceTools(SYMBOL_SPEC, {
  update: "update_symbol",
  delete: "delete_symbol",
  create: "create_symbol",
});
const groupTools = makeResourceTools(GROUP_SPEC, {
  update: "update_group",
  delete: "delete_group",
  create: "create_group",
});
const accountTools = makeResourceTools(ACCOUNT_SPEC, {
  update: "update_account",
  delete: "delete_account",
  create: "create_account",
});
const clientTools = makeResourceTools(CLIENT_SPEC, {
  update: "update_client",
  delete: "delete_client",
  create: "create_client",
});
const connectorTools = makeResourceTools(CONNECTOR_SPEC, {
  update: "update_liquidity_connector",
  delete: "delete_liquidity_connector",
  create: "create_liquidity_connector",
});
const holidayTools = makeResourceTools(HOLIDAY_SPEC, {
  update: "update_holiday",
  delete: "delete_holiday",
  create: "create_holiday",
});
const managerTools = makeResourceTools(MANAGER_SPEC, {
  update: "update_manager",
  delete: "delete_manager",
  create: "create_manager",
});

export const getGroupsSchema = z.object({});

export async function getGroups(client: RestClient) {
  return client.get("/admin/groups/query");
}

export const getGroupSchema = z.object({
  groupId: z.number().describe("Group unique identifier"),
});

export async function getGroup(client: RestClient, params: z.infer<typeof getGroupSchema>) {
  return client.get(`/admin/groups/get/${params.groupId}`);
}

export const getClientsSchema = z.object({});

export async function getClients(client: RestClient) {
  return client.get("/admin/clients/query");
}

// /admin/routing/edit ALWAYS requires If-Match, and the ETag only ever arrives on the /query
// path — RestClient keys ETags by path, so without bridging it every routing write fails with
// PRECONDITION_FAILED. Read the current config and carry its ETag onto the edit path.
async function readRoutingForWrite(client: RestClient) {
  // Take the ETag from this exact response (not the shared per-path cache) and bridge it onto
  // the edit path — /admin/routing/edit always requires If-Match.
  const { data, etag } = await readWithEtag(client, "/admin/routing/query");
  const current = data as unknown as {
    version: number;
    routing: Array<{ a: unknown[]; f?: unknown[] }>;
  };
  client.setEtag("/admin/routing/edit", etag ?? "");
  return current;
}

export const getOrderRoutingSchema = z.object({});

export async function getOrderRouting(client: RestClient) {
  return client.get("/admin/routing/query");
}

export const setOrderRoutingSchema = z.object({
  version: z.number().describe("Current routing config version (get from get_order_routing)"),
  routing: z
    .array(
      z.object({
        a: z
          .array(z.record(z.unknown()))
          .describe("Actions array (e.g. [{type:'Execute',connectorId:1}])"),
        f: z.array(z.record(z.unknown())).optional().describe("Filters array (optional)"),
      }),
    )
    .describe("Array of routing rules"),
});

export async function setOrderRouting(
  client: RestClient,
  params: z.infer<typeof setOrderRoutingSchema>,
) {
  // The caller's `version` is their statement of what they believe the config to be. If the
  // config moved since their get_order_routing, silently bridging the FRESH ETag would let a
  // stale replacement overwrite the concurrent change — so fail loudly instead.
  const current = await readRoutingForWrite(client);
  if (current.version !== params.version) {
    throw new Error(
      `Routing configuration changed since it was read (you have version ${params.version}, the server is at ${current.version}). Re-read it with get_order_routing and re-apply your change.`,
    );
  }
  return client.post("/admin/routing/edit", {
    version: params.version,
    routing: params.routing,
  });
}

export const addRoutingRuleSchema = z.object({
  actions: z
    .array(z.record(z.unknown()))
    .describe("Actions array (e.g. [{type:'Execute',connectorId:1}])"),
  filters: z
    .array(z.record(z.unknown()))
    .optional()
    .describe("Filters array (optional, e.g. [{type:'Symbol',value:'EURUSD'}])"),
});

export async function addRoutingRule(
  client: RestClient,
  params: z.infer<typeof addRoutingRuleSchema>,
) {
  const current = await readRoutingForWrite(client);

  const newRule: { a: unknown[]; f?: unknown[] } = { a: params.actions };
  if (params.filters) newRule.f = params.filters;

  const updatedRouting = [...(current.routing || []), newRule];

  return client.post("/admin/routing/edit", {
    version: current.version,
    routing: updatedRouting,
  });
}

export const removeRoutingRuleSchema = z.object({
  index: z
    .number()
    .describe(
      "Zero-based index of the routing rule to remove (use get_order_routing to see current rules)",
    ),
});

export async function removeRoutingRule(
  client: RestClient,
  params: z.infer<typeof removeRoutingRuleSchema>,
) {
  const current = await readRoutingForWrite(client);

  const routing = current.routing || [];
  if (params.index < 0 || params.index >= routing.length) {
    throw new Error(
      `Invalid index ${params.index}. Current routing has ${routing.length} rules (0-${routing.length - 1}).`,
    );
  }

  const removed = routing[params.index];
  const updatedRouting = routing.filter((_, i) => i !== params.index);

  await client.post("/admin/routing/edit", {
    version: current.version,
    routing: updatedRouting,
  });

  return { removed, remainingRules: updatedRouting.length };
}

export const getLiquidityConnectorsSchema = z.object({});

export async function getLiquidityConnectors(client: RestClient) {
  return client.get("/admin/liquidity/query");
}

export const getSymbolDetailsSchema = z.object({
  symbolId: z.number().describe("Symbol unique identifier"),
});

export async function getSymbolDetails(
  client: RestClient,
  params: z.infer<typeof getSymbolDetailsSchema>,
) {
  return client.get(`/admin/symbols/get/${params.symbolId}`);
}

// === SYMBOL EDIT (plan/commit) ===
//
// The Trade Server admin API exposes symbol writes as a single upsert endpoint,
// POST /admin/symbols/edit, which takes the FULL symbol object (same verbose shape
// get_symbols returns) and uses the object's `version` for optimistic concurrency.
// We therefore read-modify-write: GET the current symbol, apply a partial overlay,
// and POST the merged object back — preserving id/version and every untouched field.
// Confirmed against yourbourse/trade-server-samples and the admin UI SDK.

const symbolSessionSchema = z.object({
  weekDay: z.enum(["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]).describe("Day of week"),
  start: z.string().describe('Session start as "HH:MM:SS" in server time'),
  end: z.string().describe('Session end as "HH:MM:SS" in server time'),
});

export const updateSymbolPlanSchema = z.object({
  symbolId: z.number().describe("ID of the symbol to modify (from get_symbols)"),
  updates: z
    .record(z.unknown())
    .optional()
    .describe(
      "Partial map of top-level symbol fields to overwrite, using the exact field names get_symbols returns (e.g. { bidMarkup: 5, maxOrderSize: 50 }). For sessions use quoteSessions/tradeSessions instead.",
    ),
  quoteSessions: z
    .array(symbolSessionSchema)
    .optional()
    .describe(
      "Full replacement list of quote sessions (one entry per interval; repeat a weekday for intraday breaks). Omit to leave unchanged.",
    ),
  tradeSessions: z
    .array(symbolSessionSchema)
    .optional()
    .describe("Full replacement list of trade sessions. Omit to leave unchanged."),
});

// Symbols keep a friendlier surface than the generic tool (sessions are separate parameters
// rather than raw fields), but the read-modify-write itself is the shared helper — so ETag
// handling and read-only-field stripping stay identical to every other resource.
export async function updateSymbolPlan(
  client: RestClient,
  params: z.infer<typeof updateSymbolPlanSchema>,
) {
  const overlay: Record<string, unknown> = { ...(params.updates ?? {}) };
  if (params.quoteSessions !== undefined) overlay.quoteSessions = params.quoteSessions;
  if (params.tradeSessions !== undefined) overlay.tradeSessions = params.tradeSessions;
  return symbolTools.planEdit(client, params.symbolId, overlay);
}

export const updateSymbolCommitSchema = z.object({
  commitToken: z.string().describe("The commitToken returned by update_symbol_plan"),
});

export const updateSymbolCommit = (
  client: RestClient,
  params: z.infer<typeof updateSymbolCommitSchema>,
) => symbolTools.commitEdit(client, params.commitToken);

// === GROUP EDIT / DELETE (plan/commit) ===
//
// Groups use the same admin write contract as symbols: POST /admin/groups/edit is an upsert
// (id/version 0 = create) guarded by If-Match (ETag == the group version), and
// POST /admin/groups/delete takes { groupId, version } and also requires If-Match. Both bridge
// the ETag captured from the GET onto the write path (RestClient keys ETags by path).

export const updateGroupPlanSchema = z.object({
  groupId: z.number().describe("ID of the group to modify (from get_groups)"),
  updates: z
    .record(z.unknown())
    .describe(
      "Map of top-level group fields to overwrite, using the exact field names get_groups returns (e.g. { defaultLeverage: 200, marginCall: 80, stopout: 50 }).",
    ),
});

export async function updateGroupPlan(
  client: RestClient,
  params: z.infer<typeof updateGroupPlanSchema>,
) {
  return groupTools.planEdit(client, params.groupId, params.updates);
}

export const updateGroupCommitSchema = z.object({
  commitToken: z.string().describe("The commitToken returned by update_group_plan"),
});

export const updateGroupCommit = (
  client: RestClient,
  params: z.infer<typeof updateGroupCommitSchema>,
) => groupTools.commitEdit(client, params.commitToken);

export const deleteGroupPlanSchema = z.object({
  groupId: z.number().describe("ID of the group to delete (from get_groups)"),
});

export async function deleteGroupPlan(
  client: RestClient,
  params: z.infer<typeof deleteGroupPlanSchema>,
) {
  return groupTools.planDelete(client, params.groupId);
}

export const deleteGroupCommitSchema = z.object({
  commitToken: z.string().describe("The commitToken returned by delete_group_plan"),
});

export const deleteGroupCommit = (
  client: RestClient,
  params: z.infer<typeof deleteGroupCommitSchema>,
) => groupTools.commitDelete(client, params.commitToken);

// === RESOURCE CRUD (accounts, clients, liquidity connectors, symbol delete) ===
// Thin, task-shaped wrappers over the shared read-modify-write / delete helpers in
// resource-write.ts. Each pair mirrors the symbol/group tools: *_plan previews (read + diff),
// *_commit applies with If-Match. Tool names/descriptions are hand-written in register-admin.ts.

const commitTokenSchema = (planTool: string) =>
  z.object({ commitToken: z.string().describe(`The commitToken returned by ${planTool}`) });

// --- Trading accounts ---
export const updateAccountPlanSchema = z.object({
  accountId: z.number().describe("Trading account ID (login), from get_all_accounts"),
  updates: z
    .record(z.unknown())
    .describe(
      "Map of top-level account fields to overwrite, using the exact field names get_account_info returns (e.g. { leverage: 200, enabled: true, allowTrading: false, groupId: 2 }).",
    ),
});
export const updateAccountPlan = (client: RestClient, p: z.infer<typeof updateAccountPlanSchema>) =>
  accountTools.planEdit(client, p.accountId, p.updates);
export const updateAccountCommitSchema = commitTokenSchema("update_account_plan");
export const updateAccountCommit = (
  client: RestClient,
  p: z.infer<typeof updateAccountCommitSchema>,
) => accountTools.commitEdit(client, p.commitToken);
export const deleteAccountPlanSchema = z.object({
  accountId: z.number().describe("Trading account ID to delete (from get_all_accounts)"),
});
export const deleteAccountPlan = (client: RestClient, p: z.infer<typeof deleteAccountPlanSchema>) =>
  accountTools.planDelete(client, p.accountId);
export const deleteAccountCommitSchema = commitTokenSchema("delete_account_plan");
export const deleteAccountCommit = (
  client: RestClient,
  p: z.infer<typeof deleteAccountCommitSchema>,
) => accountTools.commitDelete(client, p.commitToken);

// --- Clients ---
export const getClientSchema = z.object({
  clientId: z.number().describe("Client unique identifier (from get_clients)"),
});
export const getClient = (client: RestClient, p: z.infer<typeof getClientSchema>) =>
  client.get(`/admin/clients/get/${p.clientId}`);
export const updateClientPlanSchema = z.object({
  clientId: z.number().describe("Client ID, from get_clients"),
  updates: z
    .record(z.unknown())
    .describe(
      "Map of top-level client fields to overwrite, using the exact field names get_clients returns (e.g. { clientStatus: 'Active', personFirstName: 'Jane' }).",
    ),
});
export const updateClientPlan = (client: RestClient, p: z.infer<typeof updateClientPlanSchema>) =>
  clientTools.planEdit(client, p.clientId, p.updates);
export const updateClientCommitSchema = commitTokenSchema("update_client_plan");
export const updateClientCommit = (
  client: RestClient,
  p: z.infer<typeof updateClientCommitSchema>,
) => clientTools.commitEdit(client, p.commitToken);
export const deleteClientPlanSchema = z.object({
  clientId: z.number().describe("Client ID to delete (from get_clients)"),
});
export const deleteClientPlan = (client: RestClient, p: z.infer<typeof deleteClientPlanSchema>) =>
  clientTools.planDelete(client, p.clientId);
export const deleteClientCommitSchema = commitTokenSchema("delete_client_plan");
export const deleteClientCommit = (
  client: RestClient,
  p: z.infer<typeof deleteClientCommitSchema>,
) => clientTools.commitDelete(client, p.commitToken);

// --- Liquidity connectors ---
export const getLiquidityConnectorSchema = z.object({
  connectorId: z.number().describe("Liquidity connector ID (from get_liquidity_connectors)"),
});
export const getLiquidityConnector = (
  client: RestClient,
  p: z.infer<typeof getLiquidityConnectorSchema>,
) => client.get(`/admin/liquidity/get/${p.connectorId}`);
export const updateLiquidityConnectorPlanSchema = z.object({
  connectorId: z.number().describe("Liquidity connector ID, from get_liquidity_connectors"),
  updates: z
    .record(z.unknown())
    .describe(
      "Map of top-level connector fields to overwrite, using the exact field names get_liquidity_connectors returns (e.g. { isEnabled: false, priority: 2 }). sessionParameters/symbols are arrays — pass the whole replacement array to change them.",
    ),
});
export const updateLiquidityConnectorPlan = (
  client: RestClient,
  p: z.infer<typeof updateLiquidityConnectorPlanSchema>,
) => connectorTools.planEdit(client, p.connectorId, p.updates);
export const updateLiquidityConnectorCommitSchema = commitTokenSchema(
  "update_liquidity_connector_plan",
);
export const updateLiquidityConnectorCommit = (
  client: RestClient,
  p: z.infer<typeof updateLiquidityConnectorCommitSchema>,
) => connectorTools.commitEdit(client, p.commitToken);
export const deleteLiquidityConnectorPlanSchema = z.object({
  connectorId: z
    .number()
    .describe("Liquidity connector ID to delete (from get_liquidity_connectors)"),
});
export const deleteLiquidityConnectorPlan = (
  client: RestClient,
  p: z.infer<typeof deleteLiquidityConnectorPlanSchema>,
) => connectorTools.planDelete(client, p.connectorId);
export const deleteLiquidityConnectorCommitSchema = commitTokenSchema(
  "delete_liquidity_connector_plan",
);
export const deleteLiquidityConnectorCommit = (
  client: RestClient,
  p: z.infer<typeof deleteLiquidityConnectorCommitSchema>,
) => connectorTools.commitDelete(client, p.commitToken);

// --- Symbol delete (symbol edit lives in the SYMBOL EDIT section above) ---
export const deleteSymbolPlanSchema = z.object({
  symbolId: z.number().describe("Symbol ID to delete (from get_symbols)"),
});
export const deleteSymbolPlan = (client: RestClient, p: z.infer<typeof deleteSymbolPlanSchema>) =>
  symbolTools.planDelete(client, p.symbolId);
export const deleteSymbolCommitSchema = commitTokenSchema("delete_symbol_plan");
export const deleteSymbolCommit = (
  client: RestClient,
  p: z.infer<typeof deleteSymbolCommitSchema>,
) => symbolTools.commitDelete(client, p.commitToken);

// === TIER 2: holidays (trading calendar), managers, tokens ===

// --- Holidays ---
export const getHolidaysSchema = z.object({});
export const getHolidays = (client: RestClient) => client.post("/admin/holidays/query", {});
export const getHolidaySchema = z.object({
  holidayId: z.number().describe("Holiday unique identifier (from get_holidays)"),
});
export const getHoliday = (client: RestClient, p: z.infer<typeof getHolidaySchema>) =>
  client.get(`/admin/holidays/get/${p.holidayId}`);
export const updateHolidayPlanSchema = z.object({
  holidayId: z.number().describe("Holiday ID, from get_holidays"),
  updates: z
    .record(z.unknown())
    .describe(
      "Map of top-level holiday fields to overwrite, using the exact field names get_holidays returns (e.g. { enabled: false, year: 2027, month: 12, day: 25, symbolMask: '*' }).",
    ),
});
export const updateHolidayPlan = (client: RestClient, p: z.infer<typeof updateHolidayPlanSchema>) =>
  holidayTools.planEdit(client, p.holidayId, p.updates);
export const updateHolidayCommitSchema = commitTokenSchema("update_holiday_plan");
export const updateHolidayCommit = (
  client: RestClient,
  p: z.infer<typeof updateHolidayCommitSchema>,
) => holidayTools.commitEdit(client, p.commitToken);
export const deleteHolidayPlanSchema = z.object({
  holidayId: z.number().describe("Holiday ID to delete (from get_holidays)"),
});
export const deleteHolidayPlan = (client: RestClient, p: z.infer<typeof deleteHolidayPlanSchema>) =>
  holidayTools.planDelete(client, p.holidayId);
export const deleteHolidayCommitSchema = commitTokenSchema("delete_holiday_plan");
export const deleteHolidayCommit = (
  client: RestClient,
  p: z.infer<typeof deleteHolidayCommitSchema>,
) => holidayTools.commitDelete(client, p.commitToken);

// --- Managers (manager-account permissions) ---
export const getManagersSchema = z.object({});
export const getManagers = (client: RestClient) => client.get("/admin/managers/query");
export const getManagerSchema = z.object({
  accountId: z.number().describe("Manager's trading account ID (from get_managers)"),
});
export const getManager = (client: RestClient, p: z.infer<typeof getManagerSchema>) =>
  client.get(`/admin/managers/get/${p.accountId}`);
export const getManagerSelfSchema = z.object({});
export const getManagerSelf = (client: RestClient) => client.get("/admin/managers/self");
export const updateManagerPlanSchema = z.object({
  accountId: z.number().describe("Manager's account ID, from get_managers"),
  updates: z
    .record(z.unknown())
    .describe(
      "Map of top-level manager permission fields to overwrite, using the exact field names get_managers returns (e.g. { configureSymbols: true, viewGroups: true, configureHolidays: false }).",
    ),
});
export const updateManagerPlan = (client: RestClient, p: z.infer<typeof updateManagerPlanSchema>) =>
  managerTools.planEdit(client, p.accountId, p.updates);
export const updateManagerCommitSchema = commitTokenSchema("update_manager_plan");
export const updateManagerCommit = (
  client: RestClient,
  p: z.infer<typeof updateManagerCommitSchema>,
) => managerTools.commitEdit(client, p.commitToken);
export const deleteManagerPlanSchema = z.object({
  accountId: z.number().describe("Manager's account ID to delete (from get_managers)"),
});
export const deleteManagerPlan = (client: RestClient, p: z.infer<typeof deleteManagerPlanSchema>) =>
  managerTools.planDelete(client, p.accountId);
export const deleteManagerCommitSchema = commitTokenSchema("delete_manager_plan");
export const deleteManagerCommit = (
  client: RestClient,
  p: z.infer<typeof deleteManagerCommitSchema>,
) => managerTools.commitDelete(client, p.commitToken);

// --- Access tokens (read) ---
export const getTokensSchema = z.object({});
export const getTokens = (client: RestClient) => client.post("/admin/tokens/query", {});

// === CREATE flows (clone-a-template + overrides, or a full object; id/version forced to 0) ===

const makeCreateSchema = (label: string, exampleOverrides: string) =>
  z.object({
    fromId: z
      .number()
      .optional()
      .describe(
        `Existing ${label} ID to clone as a template (recommended) — its full config is copied, then your overrides applied.`,
      ),
    object: z
      .record(z.unknown())
      .optional()
      .describe(
        `Full new ${label} object (alternative to fromId). id and version are forced to 0.`,
      ),
    overrides: z
      .record(z.unknown())
      .optional()
      .describe(`Fields to set on the new ${label}, e.g. ${exampleOverrides}.`),
  });

// Symbol
export const createSymbolPlanSchema = makeCreateSchema(
  "symbol",
  "{ name: 'EURGBP', path: 'Forex/EURGBP', description: 'Euro vs Pound' }",
);
export const createSymbolPlan = (client: RestClient, p: z.infer<typeof createSymbolPlanSchema>) =>
  symbolTools.planCreate(client, p);
export const createSymbolCommitSchema = commitTokenSchema("create_symbol_plan");
export const createSymbolCommit = (
  client: RestClient,
  p: z.infer<typeof createSymbolCommitSchema>,
) => symbolTools.commitCreate(client, p.commitToken);

// Group
export const createGroupPlanSchema = makeCreateSchema(
  "group",
  "{ name: 'Real/EUR-Standard', currency: 'EUR', defaultLeverage: 100 }",
);
export const createGroupPlan = (client: RestClient, p: z.infer<typeof createGroupPlanSchema>) =>
  groupTools.planCreate(client, p);
export const createGroupCommitSchema = commitTokenSchema("create_group_plan");
export const createGroupCommit = (client: RestClient, p: z.infer<typeof createGroupCommitSchema>) =>
  groupTools.commitCreate(client, p.commitToken);

// Holiday
export const createHolidayPlanSchema = makeCreateSchema(
  "holiday",
  "{ description: 'Christmas', year: 0, month: 12, day: 25, enabled: true, symbolMask: '*' }",
);
export const createHolidayPlan = (client: RestClient, p: z.infer<typeof createHolidayPlanSchema>) =>
  holidayTools.planCreate(client, p);
export const createHolidayCommitSchema = commitTokenSchema("create_holiday_plan");
export const createHolidayCommit = (
  client: RestClient,
  p: z.infer<typeof createHolidayCommitSchema>,
) => holidayTools.commitCreate(client, p.commitToken);

// Client
export const createClientPlanSchema = makeCreateSchema(
  "client",
  "{ clientType: 'Individual', clientStatus: 'Active', personFirstName: 'Jane', personLastName: 'Doe' }",
);
export const createClientPlan = (client: RestClient, p: z.infer<typeof createClientPlanSchema>) =>
  clientTools.planCreate(client, p);
export const createClientCommitSchema = commitTokenSchema("create_client_plan");
export const createClientCommit = (
  client: RestClient,
  p: z.infer<typeof createClientCommitSchema>,
) => clientTools.commitCreate(client, p.commitToken);

// Trading account (NOTE: a new account requires `password` in overrides/object)
export const createAccountPlanSchema = makeCreateSchema(
  "trading account",
  "{ groupId: 2, clientId: 2, leverage: 100, enabled: true, password: '<initial-password>' } — a new account REQUIRES a password",
);
export const createAccountPlan = (client: RestClient, p: z.infer<typeof createAccountPlanSchema>) =>
  accountTools.planCreate(client, p);
export const createAccountCommitSchema = commitTokenSchema("create_account_plan");
export const createAccountCommit = (
  client: RestClient,
  p: z.infer<typeof createAccountCommitSchema>,
) => accountTools.commitCreate(client, p.commitToken);

export const healthCheckSchema = z.object({});

export async function healthCheck(client: RestClient) {
  return client.get("/now");
}

// === ADMIN REPORTING / LOOKUPS (read-only) ===

export const getJournalSchema = z.object({
  fromTime: z.number().describe("Start time (microseconds since epoch)"),
  toTime: z.number().describe("End time (microseconds since epoch)"),
  mask: z.string().optional().describe("Substring/glob filter over journal messages"),
  severities: z
    .array(z.enum(["trace", "debug", "info", "warning", "error", "critical"]))
    .optional()
    .describe("Only these severities. Omit for all"),
  maxResults: z.number().optional().describe("Max entries to return"),
});

export async function getJournal(client: RestClient, params: z.infer<typeof getJournalSchema>) {
  const body: Record<string, unknown> = { fromTime: params.fromTime, toTime: params.toTime };
  if (params.mask !== undefined) body.mask = params.mask;
  if (params.severities !== undefined) body.severities = params.severities;
  if (params.maxResults !== undefined) body.maxResults = params.maxResults;
  return client.post("/admin/journal/query", body);
}

export const getStatementsSchema = z.object({
  type: z.enum(["Daily", "Monthly"]).describe("Statement period"),
  date: z.string().describe('Statement date as "YYYY-MM-DD"'),
  ...accountFilterSchema,
  orders: z.boolean().optional().describe("Include orders in the statement. Default false"),
  positions: z.boolean().optional().describe("Include positions in the statement. Default false"),
  maxResults: z.number().optional().describe("Max results (server caps at 250)"),
});

export async function getStatements(
  client: RestClient,
  params: z.infer<typeof getStatementsSchema>,
) {
  const body: Record<string, unknown> = {
    type: params.type,
    date: params.date,
    // accountFilter is REQUIRED here; default to every group so a caller who omits it still
    // gets a valid request rather than a rejected one.
    accountFilter: buildAccountFilter(params) ?? { groupMasks: ["*"] },
  };
  if (params.orders !== undefined) body.orders = params.orders;
  if (params.positions !== undefined) body.positions = params.positions;
  if (params.maxResults !== undefined) body.maxResults = params.maxResults;
  return client.post("/admin/statements/query", body);
}

export const getEmailServicesSchema = z.object({});

export const getEmailServices = (client: RestClient) => client.get("/admin/email-service/query");

export const findClientByExternalIdSchema = z.object({
  clientExternalId: z.string().describe("The client's external identifier"),
});

export async function findClientByExternalId(
  client: RestClient,
  params: z.infer<typeof findClientByExternalIdSchema>,
) {
  return client.post("/admin/clients/query-by-external-id", {
    clientExternalId: params.clientExternalId,
  });
}

// Granting a NEW manager needs its own tool: update_manager_plan reads the existing record first,
// which 404s for an account that is not a manager yet. The manager resource is keyed by
// `accountId` (not `id`), and a new one is created with `version` 0 and no If-Match.
/** Every boolean permission set to false, so a fresh manager starts with no rights. */
function denyAllPermissions(record: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(record)) out[k] = typeof v === "boolean" ? false : v;
  return out;
}

export const createManagerPlanSchema = z.object({
  accountId: z.number().describe("Trading account to grant manager permissions to"),
  fromId: z
    .number()
    .optional()
    .describe("Existing manager's account ID to copy permissions from (from get_managers)"),
  groups: z
    .string()
    .optional()
    .describe(
      'Group masks this manager may administer, e.g. "*" for every group or "Real/*". Required by the server; defaults to "*".',
    ),
  permissions: z
    .record(z.boolean())
    .optional()
    .describe(
      "Permission flags to set, using the exact field names get_managers returns (e.g. { viewSymbols: true, configureSymbols: true }). Applied on top of the copied template when fromId is given.",
    ),
});

const CREATE_MANAGER_DISCLOSURE =
  "You are confirming the LIVE CREATION of a manager (granting server-wide admin permissions to an account) via an AI assistant. Review the permissions, then call create_manager_commit with this commitToken. Nothing is written until you commit.";

export async function createManagerPlan(
  client: RestClient,
  params: z.infer<typeof createManagerPlanSchema>,
) {
  // The manager record must be COMPLETE: the server rejects a sparse body (just the flags you
  // care about) with "Invalid body". With no template to clone, start from the signed-in manager's
  // own record with every permission turned OFF, so the new manager ends up with exactly the flags
  // that were asked for and nothing else.
  const template =
    params.fromId != null
      ? await readFresh(client, `/admin/managers/get/${params.fromId}`)
      : denyAllPermissions(await readFresh(client, "/admin/managers/self"));
  const next: Record<string, unknown> = {
    ...template,
    ...(params.permissions ?? {}),
    accountId: params.accountId,
    version: 0,
    // /admin/managers/self omits `groups`, but the edit endpoint requires it — without it the
    // server rejects the body as "Invalid body" (observed live).
    groups: params.groups ?? (template.groups as string | undefined) ?? "*",
  };
  return {
    resource: "manager",
    action: "create",
    willCreate: next,
    commitToken: issuePlan({ path: "/admin/managers/edit", object: next }, "create_manager"),
    disclosure: CREATE_MANAGER_DISCLOSURE,
  };
}

export const createManagerCommitSchema = commitTokenSchema("create_manager_plan");

export const createManagerCommit = (
  client: RestClient,
  p: z.infer<typeof createManagerCommitSchema>,
) => managerTools.commitCreate(client, p.commitToken);

// Liquidity connectors are created through the same upsert as every other config resource. Their
// `sessionParameters` carry FIX credentials (host, port, SenderCompID, password …) in the clear —
// that is how the API returns them, and an administrator configuring a feed needs to see and set
// them, so they are passed through unredacted.
export const createLiquidityConnectorPlanSchema = z.object({
  fromId: z
    .number()
    .optional()
    .describe(
      "Existing connector ID to clone as a template (from get_liquidity_connectors) — copies its type, session parameters and symbols, which you then override.",
    ),
  object: z
    .record(z.unknown())
    .optional()
    .describe(
      "Full connector object (alternative to fromId): type ('YB-FIX-QUOTES' | 'YB-FIX-TRADES' | 'ONEZERO-FIX-QUOTES' | 'ONEZERO-FIX-TRADES'), priority, isEnabled, sessionParameters, parameters, symbols. id and version are forced to 0.",
    ),
  overrides: z
    .record(z.unknown())
    .optional()
    .describe(
      "Fields to set on the new connector, e.g. { isEnabled: false, priority: 2, symbols: [1, 50], sessionParameters: [{ name: 'Host', stringValue: 'fix.example.com' }, { name: 'Password', passwordValue: '…' }] }.",
    ),
});

export const createLiquidityConnectorPlan = (
  client: RestClient,
  p: z.infer<typeof createLiquidityConnectorPlanSchema>,
) => connectorTools.planCreate(client, p);

export const createLiquidityConnectorCommitSchema = commitTokenSchema(
  "create_liquidity_connector_plan",
);

export const createLiquidityConnectorCommit = (
  client: RestClient,
  p: z.infer<typeof createLiquidityConnectorCommitSchema>,
) => connectorTools.commitCreate(client, p.commitToken);
